version: "3"

tasks:
    # The `build:` tasks below are used together for production builds of a project
    build:templ:
        cmds:
            - go tool templ generate
        sources:
            - "**/*.templ"
        generates:
            - "**/*_templ.go"

    build:
        dir: example
        cmds:
            - go build -tags=prod -o bin/example-server ./cmd/server
        deps:
            - build:templ
